# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='except_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
